### ISSUE TITLE
US1 – List of Outivities

### ISSUE THREAD

**Issue by Julia-Pickel** [BirkBee/outivities-app#1]
## Value proposition

**As an** outdoor enthusiast
**I want to** see a list of all outdoor activities
**so that I can** explore and choose activities that interest me.

## Description

![Image](https://github.com/BirkBee/outivities-app/assets/145296722/dc640e7d-5b05-4c2f-97fa-9d7fb29aca26)

## Acceptance criteria

- [x] A headline with the content *"All Outivities"* is displayed at the top of the list
- [x] All activities are displayed as a list
- [x] Each activity shows a dummy image
- [x] Each activity shows a dummy title
- [x] Each activity shows a dummy location
- [x] The list scrolls vertically

## Tasks

- [x] Create feature-branch
- [x] Create example data
- [x] Create Card Component
- [x] Create List Component
- [x] Render Cards in List Component
- [x] Render List in Homepage
- [x] Add error handling

**Comment by JessicaLoers** [comment]
**Hello @Julia-Pickel @BirkBee @ykolomytseva @Philipp-Hess**  

**very nice 1st User Story.**  ✨

I have a few petty remarks:

**Value Proposition**
Essentially, the action and the user goal convey the same thing. _"We see a list of activities with the goal to see a list of activities."_ (To exaggerate a little 🙂)

For this reason, I would like to suggest the following change.

**As an** outdoor enthusiast
**I want to** see a list of all outdoor activities
**so that I can** explore and choose activities that interest me. ⬅️


**Acceptance Criteria**
- [ ] A header is displayed at the top (fixed)
⬇️
- [ ] A headline with the content _"All Outivities"_ are displayed at the top of the list. 

_As a user, I'm not really sure what a header is. In addition, this criteria could be a little more precise._ 


My comments are nitpicking at a high level. You all are doing a great job. Keep it up 🙌

**Comment by Julia-Pickel** [comment]
Hi Jessica, thank you for your helpful comments! 🙌
We updated the user story and changed the things you recommended.

**Comment by JessicaLoers** [comment]
Yeah, well done.
