### ISSUE TITLE
US7 - Favorite Outivities

### ISSUE THREAD

**Issue by Julia-Pickel** [BirkBee/outivities-app#10]

**Comment by BirkBee** [comment]
## Favourite Outivities

**As an** outdoor enthusiast 
**I want to** add my favorite Outivities to a favorites page
**in order to** have a good overview of what Outivities matter most to me

## Description






![Image](https://github.com/BirkBee/outivities-app/assets/137433498/79e75f47-c1a4-4b0e-9fc6-3ab3d9b3960c)











## Acceptance criteria

- [ ] A favourite button is added in the navbar
- [ ] Clicking the favourites button adds the Outivity to the favourites page
- [ ] Clicking the favourite button in the navbar navigates to the favourites page
- [ ] A list of the favourite Outivities can be viewed on the favourites page
- [ ] To remove the outivity from the favourites page, user can toggle the ❤ 
- [ ] The heart is displayed on All Outivities list and on the Details page and can be toggled on both pages

## Tasks

- [ ] Create favourites page component
- [ ] Create favourite button and add it to navbar, which is displayed on every page in the navbar
- [ ] Create favourites button, which is displayed on every Outivity image on the Details page and the Home page
- [ ] Add a toggle function to the favourites button, which changes ♡ to ❤  and adds Outivity to favourites

**Comment by feivlinus** [comment]
Such a fine User Story. So much good. Everything clear. 
Keep on! 👍


![Image](https://github.com/BirkBee/outivities-app/assets/8994153/4a7226c6-d902-478e-8f0e-33ccd4e1ac7c)
