### ISSUE TITLE
US8 - Searchbar

### ISSUE THREAD

**Issue by Julia-Pickel** [BirkBee/outivities-app#12]
## Value proposition

As a user
I want the ability to quickly find specific outivities
that match my interests or preferences

## Description

![Image](https://github.com/BirkBee/outivities-app/assets/137433498/e7774278-44cf-4c17-8a9f-7ac6220b8ffa)

## Acceptance criteria

- [ ] The search bar should be prominently displayed on the Home page
- [ ] The search bar should feature an input field
- [ ] The search bar should include search button or icon that users can click on to initiate the search
- [ ] As user type their search queries, the search bar should provide real-time suggestions based on the entered text
- [ ] Upon submitting a search, results would be presented and listed alphabetically 
- [ ] The search bar should be responsive and adapting to different screen sizes

## Tasks

- [ ] Update the design and implement the search bar with an input field
- [ ] Implement a mechanism to provide real-time auto-suggestions based on an input
- [ ] Integrate a search button or an icon
- [ ] Define the criteria for generating relevant suggestions (location or title)
- [ ] Implement responsive design and adapt to different screen sizes
- [ ] Implement error message in case no results are found

**Comment by luederb** [comment]
Wow, nicely done 💪. Clear and precise 👌
Looks good to us!
