### ISSUE TITLE
US9 - Weather API

### ISSUE THREAD

**Issue by Julia-Pickel** [BirkBee/outivities-app#13]

**Comment by Philipp-Hess** [comment]
## Value proposition

**As an** outdoor enthusiast
**I want to** access current weather information for planning outdoor activities
**so that** I can make informed decisions based on the weather conditions.

## Description

![Image](https://github.com/BirkBee/outivities-app/assets/145116105/68234ddc-b241-4ad4-b28e-0c5a2025049a)



## Acceptance Criteria
 
- [ ] On the details page, the current weather conditions for the selected location are displayed.
- [ ] The weather information includes temperature, weather description, and any other relevant details
- [ ] The displayed weather information is updated dynamically based on real-time data from the weather api.


## Tasks

- [ ] Implement Weather API integration to fetch current weather information.
- [ ] Design and implement the presentation of temperature, weather description, and other relevant information on the details page.
- [ ] Ensure that the displayed weather information based on real-time data from the Weather API for the selected location is dynamically updated.
- [ ] Implement error handling in case the weather api could not be fetched

**Comment by lennart-kaminsky** [comment]
Nice! I really like this part of your app 🌞 ⛈️ 
On the wireframe it seems like you don't want to give the displayed weather a lot of space on your details page. Only in the top right, right? (left, left, forward and back 🕺👯‍♂️🙄). Im curious, how this will look in the end!

LGTM HEGDL
