### ISSUE TITLE
US10 - Map Overview

### ISSUE THREAD

**Issue by BirkBee** [BirkBee/outivities-app#14]

**Comment by BirkBee** [comment]
## Map overview

As an outdoor enthusiast
I want to see the location of my outivity on a map, to be able to see where the location is exactly and to plan my activity.

## Description



![Image](https://github.com/BirkBee/outivities-app/assets/129008225/d3889345-9339-440c-9e74-fb9973dc0e08)



## Acceptance criteria

- [ ] On the details page, the current location for the selected location is displayed in a mapbox.
- [ ] The location is pinned on the map
- [ ] The pin matches the given location


## Tasks

- [ ] Implement a map on the details page
- [ ] Design and implement the presentation of the map on the details page.
- [ ] Display a pin on the location of the outivity
- [ ] Implement error handling in case the map doesn't work

**Comment by Shahab-Ziaeian** [comment]
Very nice US, LGTM 🙌 
You decided to structure your US slim and come to the point, what I like 😊
