### ISSUE TITLE
US6 – Image Upload

### ISSUE THREAD

**Issue by BirkBee** [BirkBee/outivities-app#15]
## Image Upload

**As an** outdoor enthusiast,
**i want to** upload a picture of an Outivity,
**so I can** use pictures from my gallery

## Description

![Image](https://github.com/BirkBee/outivities-app/assets/145116105/5d6e74c9-70c5-4f2f-ba10-feac0a24f19e)

## Acceptance Criteria
- [ ] An upload button for the image is added in the form where the user can create a new Outivity
- [ ] The user is informed that only certain image formats are allowed (png, jpg, jpeg and webp)
- [ ] Clicking the upload button opens up a "picker" where the user can select an image from his device
 Afterwards the selected image is displayed as selected in the form
- [ ] After creating a new Outivity, the image is than visible together
with the other information the user typed into the form, both on the home and the details page
- [ ] Next to the upload is a "removeButton" to remove the selected image in the "Create a new Outivity" process

## Tasks
- [ ] create an "uploadButton" which is displayed in the create form
of a new Outivity
- [ ] add the attribute `accept=".png, .jpeg, .jpg, .webp"` to the image input element
- [ ] create a "removeButton" which is located next to the "uploadButton"
- [ ] cloudinary is used to store the image

**Comment by lennart-kaminsky** [comment]
Hey Team Outivities! 🌲🚲🐻 
That's a really nice feature you are going to add to your app!

You might wanna think about informing the user about the upload criteria and/or handling errors that occur during the upload process though (e.g. image size, format...). 

Apart from that is is very clear what you are planning to do here. Keep it up! ✌

**Comment by Julia-Pickel** [comment]
Hey Lennart,

thank you for taking your time to read through our US!!  🙌 

That's a very good point! We've added an upload criteria related to the image format.
We will not set any further restrictions for now, but we will keep this in mind and do so later on if necessary.

**Comment by lennart-kaminsky** [comment]
Of course! :) 

As long as you will keep it in mind and also handle upload errors that might occur, you'll most likely be fine! Keep it up! ✌
