### ISSUE TITLE
US2 – Details Page

### ISSUE THREAD

**Issue by Julia-Pickel** [BirkBee/outivities-app#2]
## Value proposition

**As an** outdoor enthusiast
**I want to** see a details page of the outdoor activity
**so that I can** get all essential info.

## Description

![Image](https://github.com/BirkBee/outivities-app/assets/145296722/92cde7f2-a39a-4a60-90e4-157269f11387)

## Acceptance criteria

- [x] Clicking an Outivity from the list to show details page
- [x] A dummy image is displayed
- [x] The Outivity title is displayed
- [x] The location with the city name and country is shown
- [x] A description is shown
- [x] A navbar is displayed at the bottom (fixed)
- [x] An Icon is implemented and when clicked gets the user to the Home page
- [x] Home link to get back to home page in nav bar

## Tasks

- [x] Create a Button to get to the individual Details page
- [x] Implement a Dummy image
- [x] Add a title to the page
- [x] Add a location for the activity
- [x] Add a description text of the activity
- [x] Create a navbar to get back to home page "/" 
- [x] Implement a svg of a house to the navbar
- [x] Add error handling

**Comment by lennart-kaminsky** [comment]
Very nice user story! 🙌

We have some suggestions you might want to think about:
- [ ] In the AC, specify the type of location that is shown, e.g. a location _name_ or _address_
- [ ] At this point of your project we don't really see the added benefit for user to add a navigation bar. One single <mark>Back to list</mark>-Link could be enough at this point.

We're looking forward to see more of your app!

**Comment by Julia-Pickel** [comment]
Hey, thanks for your feedback! 🙌

As you suggested we changed the type of location to be more specific here:
- [ ] The location with the city name and country is shown

We discussed your point with the navigation bar / back-button and decided to leave the navbar since the "house icon" is our back button.

**Comment by GoekhanAgkurt** [comment]
hey @Julia-Pickel , 

the location description looks good to us. We unterstand your decision to leave a navbar. 

keep up the great work!  🚀
