### ISSUE TITLE
US12 – Implement MongoDB

### ISSUE THREAD

**Issue by Julia-Pickel** [BirkBee/outivities-app#21]

**Comment by Philipp-Hess** [comment]
## Value proposition

**As an** outdoor enthusiast
**I want** my data to be securely stored and accessible across devices,
**so that** I can have a consistent and personalized experience.

## Description



![Image](https://github.com/BirkBee/outivities-app/assets/145116105/f05301ac-38c5-4008-8d00-38515c15d2d7)



## Acceptance Criteria
 
- [ ] The user's custom outivity including the name and additional details is stored in the MongoDB database.
- [ ] MongoDB is used to create a new outivity.
- [ ] The MongoDB collection for custom outivities accommodates all relevant details provided 
        by the user.
- [ ] Changes made by the user are reflected in MongoDB.
- [ ] Deleting an outivity removes the selected outivity from MongoDB.

## Tasks

- [ ] Create a MongoDB database for outivities.
- [ ] Develop a schema and a collection in MongoDB.
- [ ] Develop functionality to Create, Read, Update, and Delete Outivities.
- [ ] Implement error handling for MongoDB connection issues.

**Comment by Roland-Hufnagel** [comment]
Looks good. 👍

**Comment by Alexander-Iantbelidze** [comment]
hello there, only one US for the whole DB? Interesting... do not forget about the "loading..." handling. Best regards! :)
