### ISSUE TITLE
US11 – API Fetching Location

### ISSUE THREAD

**Issue by BirkBee** [BirkBee/outivities-app#25]
##  API Fetching Location

As an outdoor enthusiast
 **I want to** see the actual location for the created outivity 
**so that** I can have a personalized and location-specific experience.

## Description

![Image](https://github.com/BirkBee/outivities-app/assets/129008225/d3889345-9339-440c-9e74-fb9973dc0e08)

## Acceptance criteria

- [ ] The map on the details page shows the right location for the created outivity.
- [ ] The retrieved location information is corresponding to the chosen location for the custom outivity.
- [ ] API response to ensure the custom outivity is correctly linked to the chosen location.
- [ ] the fetched location dynamically updates based on the location data associated with the custom outivity.

## Tasks

- [ ] Select and integrate an API for fetching location data.
- [ ] Implement a map for a new created outivity and show it on the details page with the correct location.
- [ ] Display a pin on the map at the location of the outivity.
- [ ] Implement error handling in case the api fetch doesn't work

**Comment by Roland-Hufnagel** [comment]
Hi team! I do not really understand the difference to US10.  Please define the AC more clearly to better understand the purpose of this US.
