### ISSUE TITLE
US3 – Create new Outivity

### ISSUE THREAD

**Issue by Julia-Pickel** [BirkBee/outivities-app#3]
## Value proposition

**As an** outdoor enthusiast
**I want to** be able to add new activities myself
**so that I can** share my own experience through this App.

## Description

![Image](https://github.com/BirkBee/outivities-app/assets/145296722/6b613188-1874-4758-9573-4d7af401be05)

## Acceptance criteria

- [ ] An icon of a plus is added to the navbar
- [ ] When clicking on a plus new page with a form opens up
- [ ] There is a placeholder image 
- [ ] You can set your *Outivity* Title
- [ ] There is an option to add a location where the activity can be found
- [ ] You can write a description with all essential info
- [ ] An error occurs if the user tries to send an empty form
- [ ] wrong inputs have to be intercepted
- [ ] You can cancel the *Outivity* creation and go back to the Homepage
- [ ] You can save your new *Outivity*

## Tasks

- [ ] Navbar is displayed on all pages and fixed at the bottom of the pages
- [ ] Create a link to get to the *"Add new Outivity"* page
- [ ] Add a svg of a plus to the navbar
- [ ] Create a form displayed as a grid
- [ ] Implement feature to add placeholder image
- [ ] Create an input field with a placeholder text and a label named *"Outivity Title"*
- [ ] Create an input field with a placeholder text and a label named *"Location"*
- [ ] Create an input field with a placeholder text and a label named *"Description"*
- [ ] Set a focus on the input field of the *Outivity* Title 
- [ ] Create a cancel button that links to the Homepage
- [ ] Create a save button and store the typed in data with the useState-method
- [ ] Create a toast message that pops up when an empty form is saved
- [ ] Add error handling

**Comment by onemanwenttomow** [comment]
>  Create a save button that stores the typed in data in the local storage

Is the rest of your data already in local storage? If not i would just add it to the state of your app for now and make user storage a separate user story.

**Comment by Julia-Pickel** [comment]
Thanks Pete for your advice!

That's a very good point. We changed our task according to your feedback and we will use the useState-method for now.
