### ISSUE TITLE
US11 – Map Overview with Individual Markers

### ISSUE THREAD

**Issue by Julia-Pickel** [BirkBee/outivities-app#30]
# Map overview page

As an outdoor enthusiast
I want to see the location of all existing outivities on a world map, to be able to see where all the locations and to plan my Outivity™

## Description

![Image](https://github.com/BirkBee/outivities-app/assets/129008225/126040bf-105a-45d6-9eb1-0d94a05e8f0a)

## Acceptance criteria

- [ ] In the nav bar a new location icon is viseable, when clicked it takes the user to the Map overview page
- [ ] The locations are pinned on the world map
- [ ] The pins match the given locations
- [ ] A info over the pin shows the location and a link, when clicked directs to the details page

## Tasks

- [ ] Create a map page
- [ ] Add a pin to the nav bar which directs to the map overview
- [ ] Display the pins of all Outivities
- [ ] Change color of selected pin
- [ ] Add al info above pin when clicked and implement a link to direct to the details page of the Outivity™

**Comment by lennart-kaminsky** [comment]
LGTM! 🚀 

Maybe you want to think of a starting position for the map or a location mark for the user's position, too. But if you don't plan on doing so it doesn't have to be part of the AC of course. 

Keep it up! ❤

**Comment by Julia-Pickel** [comment]
We decided to drop the part "Change color of selected pin" of the tasks and instead highlighted the user's location by adding a different color to the marker.
Besides that, the selected pin is highlighted by a pop-up window.
