### ISSUE TITLE
US4 – Delete Outivity

### ISSUE THREAD

**Issue by Julia-Pickel** [BirkBee/outivities-app#4]
## Delete Outivity

**As an** outdoor enthusiast 
**I want to** be able to delete activities
**so that I can** get rid of irrelevant Outivities

## Description

![US4 – Delete Outivity](https://github.com/BirkBee/outivities-app/assets/145296722/c6343f47-14e8-4e46-8115-701b743e9492)

## Acceptance criteria

- [ ] A delete button is visible on the Details page
- [ ] When clicking on delete button, you will be asked if you really want to delete the activity
- [ ] After confirming the deletion you will go back to the Home Page 
- [ ] After canceling the deletion the confirm dialog will disappear and you stay on the Details Page 

## Tasks

- [ ] Create a delete button on the Details Page
- [ ] Create delete function which gets called on confirm true
- [ ] Create a confirm dialog that appears when clicking on delete to remove the item 
- [ ] Link back to the Home Page by clicking "okay" or stay on the same page by clicking "cancel"

**Comment by onemanwenttomow** [comment]
>  When clicking on delete button, you will be asked if you really want to delete an activity

Will there be some kind of Dialog? What will that look like?

Will there be the option for the user the cancel the deletion if they change their mind?

You will need to think about the conditional rendering of this Dialog and how to achieve this.

**Comment by Julia-Pickel** [comment]
Thank you for your feedback Pete !!

We made some changes and updated our user story.
We hope it's better now? :)

**Comment by GoekhanAgkurt** [comment]
Hi @Julia-Pickel ,

looks good to us.

Maybe you can specify your third acceptance criteria like this:
After confirming the deletion you will go back to the the Home Page that does not include the deleted outivity.
