### ISSUE TITLE
US5 – Edit Outivity

### ISSUE THREAD

**Issue by BirkBee** [BirkBee/outivities-app#8]
## Edit Outivity

**As an** outdoor enthusiast 
**I want to** edit Outivities
**in order to** make essential modifications

## Description

![Image](https://github.com/BirkBee/outivities-app/assets/145296722/1dcfe8a7-fb2f-4bdb-a254-ced4b5a8b6d0)

## Acceptance criteria

- [ ] An edit button is displayed on the Details Page of every Outivity
- [ ] Clicking the edit button leads to `OutivityForm`
- [ ] All input-fields are prefilled with original text to guide user through the form
- [ ] All fields => Image URL, Outivity`s name, area, country and description can be edited
- [ ] Button "cancel changes" at bottom of the form leads back to Details Page without changes
- [ ] Button "save changes" at bottom of the form saves changes and leads to updated Details Page

## Tasks

- [ ] Create component `EditButton` that is displayed on each Details Page
- [ ] Edit button leads to `OutivityForm`
- [ ] Change form to have a dynamic heading: "Add Outivity" when using it for adding a new Outivity and "Edit Outivity" when editing an existing Outivity
- [ ] Create link component `CancelChangesButton` that redirects back to the Details Page
- [ ] Create button `SaveChangesButton` that updates Outivity and redirects to the Details Page

**Comment by luederb** [comment]
Hey Team, 
great work! 

We have some ideas about your acceptance criteria: 
- Maybe you want to change the order of input fields in your form, so that it matches the order of the details on the details page. Specifically: Maybe change the order of the "Name of Outivity" and the "Image" Input fields. 
- It would be more precise and better to understand of the user, if the "Image" Label would be "Image URL", since at this point of your app, a user can only enter a url. This way, no one gets confused to try to insert an actual PNG or so into the form 😁😉
- You might wanna add in your AC, which input fields are required in the edit (and add) form.

**Comment by ykolomytseva** [comment]
Hi! Thank you for your suggestions, we listened to them and made some changes 😉

**Comment by Roland-Hufnagel** [comment]
Hello Outivity Team,
this looks very good but one thing is a bit confusing: The pop-up message. You don't describe the behaviour of the two buttons in the pop-up messeage in your AC. And the message itself is also a bit confusing: When you ask: ' Are you sure you want to discard your unsaved changes?' the answers 'Cancel' and 'OK' can be missunderstood. 
My personal suggestion for this is: You don't need a pop-up message for this case. One button 'Cancel' and one button 'Save' would be fine. 

So either remove the pop-up message or describe more exact the behaviour of the buttons inside.

**Comment by Julia-Pickel** [comment]
Hey @Roland-Hufnagel,

thank you for taking your time to read through our US!! 🙌

We discussed the "pop-up message"-topic within our team and decided to drop it for now.
You can see the update in the description image.

**Comment by Roland-Hufnagel** [comment]
Please rework your AC as well.

**Comment by Julia-Pickel** [comment]
Careless mistake.... 🫠
Thank you for rereading through!!

**Comment by vlatkojuric** [comment]
LGTM ,nice work.



![Image](https://github.com/BirkBee/outivities-app/assets/145024927/49a31365-b4aa-42ac-a519-b4e2c6726152)
